//Generated by AIOCodeGen.
#import "ServiceGateway.h"
#import "{{service_name}}_{{name}}.h"
 
 @implementation {{service_name}}_{{name}} 
 - (void)onCall:(void (^)({{return_oc_type}}))result {{#args}}{{name}}:({{oc_ob_type}}){{name}} {{/args}}{
    //Add your handler code here!
 	//TODO:
 }
 #pragma mark - Do not edit these method.
 - (void)__flutter_p_handler_{{name}}:(NSDictionary *)args result:(void (^)({{return_oc_type}}))result {
     [self onCall:result {{#args}}{{name}}:args[@"{{name}}"] {{/args}}];
 }
 + (void)load{
     [[ServiceGateway sharedInstance] registerHandler:[{{service_name}}_{{name}} new]];
 }
 - (NSString *)returnType{
   return @"{{return_oc_type}}";
 }
 - (NSString *)service{
   return @"{{service_name}}";
 }
 @end
