//Generated by AIOCodeGen do not edit!
#import "FlutterServiceTemplate.h"

 @interface Service_{{service_name}} : NSObject
 + (FlutterServiceTemplate *)service;
 {{#native_msg}}+ (void){{name}}:(void (^)({{return_oc_ob_type}}))resultCallback {{#args}}{{name}}:({{oc_ob_type}}){{name}} {{/args}};
 {{/native_msg}}
 @end
